language: rust
rust:
  - 1.24.0
  - 1.23.0
  - 1.22.0
  - 1.21.0
  - 1.20.0
  - beta
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

cache: cargo

script:
  - cargo build --release
  - cargo test --all --release
  - cargo test --all --release -- --ignored

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pietroalbini"
    template:
      - "Build %{result} for %{repository_slug} on branch %{branch} (%{commit})."
      - "More details: %{build_url}"
    use_notice: true
    skip_join: true
