---

site_name: Fisher documentation
copyright: Created by <a href="https://www.pietroalbini.org">Pietro Albini</a>

pages:
  - "Home page": "index.md"
  - "Introduction":
    - "Why you should use Fisher": "why.md"
    - "Installing Fisher": "install.md"
  - "Tutorials":
    - "Automatic deploy from GitHub": "tutorial/auto-deploy.md"
    - "Send emails when scripts fails": "tutorial/failure-email.md"
  - "Features":
    - "Monitoring with status hooks": "features/status-hooks.md"
    - "Rate limits": "features/rate-limits.md"
    - "Third-party providers": "features/providers.md"
  - "Documentation":
    - "The configuration file": "docs/config.md"
    - "Configuration comments": "config-comments.md"
    - "Scripts execution context": "env.md"
  - "Supported providers":
    - "Standalone provider": "providers/standalone.md"
    - "GitHub provider": "providers/github.md"
    - "GitLab provider": "providers/gitlab.md"
  - "Other information":
    - "Changelog": "changelog.md"

theme:
  name: null
  custom_dir: theme

extra:
  navbar:
    "Source code": https://github.com/pietroalbini/fisher
    "Report an issue": https://github.com/pietroalbini/fisher/issues/new

docs_dir: src
site_dir: build
